using Moonlark.Native.Engineering.Core;

namespace Moonlark.Native.Engineering.Generation;

/// <summary>Renders NativeBuildContract.g.cs from the pin, the family version and the header-derived export inventory.</summary>
internal static class NativeBuildContractSource
{
    internal static Result<string> Render(LibchdrAuthority authority, IEnumerable<string> exports)
    {
        (string Name, string Value)[] constants =
        [
            ("FamilyVersion", authority.ManagedVersion),
            ("UpstreamVersion", authority.Pin.UpstreamVersion),
            ("UpstreamCommit", authority.Pin.Commit),
            ("ChdHeaderSha256", authority.Pin.Headers[Authorities.HeaderPaths[0]]),
            ("CoreTypesSha256", authority.Pin.Headers[Authorities.HeaderPaths[1]]),
        ];
        string[] names = exports.Order(StringComparer.Ordinal).ToArray();
        string? unsafeValue = constants.Select(constant => constant.Value).Concat(names).FirstOrDefault(value => !IsPlainLiteral(value));
        if (unsafeValue is not null) return new Failure("Contract value cannot be emitted as a plain C# string literal: " + unsafeValue);
        string[] lines =
        [
            "// <auto-generated />", "namespace Moonlark.Libchdr.Internal;", "",
            "internal static class NativeBuildContract", "{",
            .. constants.Select(constant => $"    internal const string {constant.Name} = \"{constant.Value}\";"),
            "    private static readonly string[] ExportNames =", "    [",
            .. names.Select(name => $"        \"{name}\","),
            "    ];",
            "    internal static System.ReadOnlySpan<string> Exports => ExportNames;",
            "}", "",
        ];
        return string.Join('\n', lines);
    }

    /// <summary>Printable ASCII without quote or backslash needs no escaping in C#, matching the original JSON-quoted form.</summary>
    private static bool IsPlainLiteral(string value) => value.All(character => character is >= ' ' and <= '~' and not '"' and not '\\');
}
