// <auto-generated />
namespace Moonlark.Libchdr.Internal;

internal static class NativeBuildContract
{
    internal const string FamilyVersion = "1.0.0-preview.1";
    internal const string UpstreamVersion = "v0.3.0-116-g607694c";
    internal const string UpstreamCommit = "607694ca0812edfc9cc2030c64634fc2393668de";
    internal const string ChdHeaderSha256 = "a318ad8a93050bbe33fdc18dcddc1b433d1840d2f09e42166e090ad5838f5fe4";
    internal const string CoreTypesSha256 = "f573f4ddf8960bff863d1e8f3513acad71a22807a18eccb634a4a4519cb88d72";
    private static readonly string[] ExportNames =
    [
        "chd_close",
        "chd_core_file",
        "chd_error_string",
        "chd_get_cache_budget",
        "chd_get_cache_stats",
        "chd_get_header",
        "chd_get_metadata",
        "chd_open",
        "chd_open_core_file",
        "chd_open_core_file_callbacks",
        "chd_open_file",
        "chd_precache",
        "chd_read",
        "chd_read_header",
        "chd_read_header_core_file",
        "chd_read_header_core_file_callbacks",
        "chd_read_header_file",
        "chd_set_cache_budget",
        "moonlark_chdr_build_info",
    ];
    internal static System.ReadOnlySpan<string> Exports => ExportNames;
}
