<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Moonlark.Native.Engineering</RootNamespace>
    <IsPackable>false</IsPackable>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Moonlark.Native.Engineering.Tests" />
  </ItemGroup>
</Project>
