namespace Moonlark.Libchdr;

/// <summary>An immutable, strictly parsed text CD or GD-ROM track metadata entry.</summary>
public readonly record struct ChdCdTrack
{
    internal const int MaximumMetadataBytes = 512;

    internal ChdCdTrack(uint number, ChdCdTrackType type, ChdCdSubcodeType subtype, uint frames,
        uint pregapFrames, ChdCdTrackType? pregapType, ChdCdSubcodeType pregapSubtype,
        bool pregapStored, uint postgapFrames, uint padFrames, ChdMetadataTag metadataTag)
    {
        Number = number;
        Type = type;
        Subtype = subtype;
        Frames = frames;
        PregapFrames = pregapFrames;
        PregapType = pregapType;
        PregapSubtype = pregapSubtype;
        PregapStored = pregapStored;
        PostgapFrames = postgapFrames;
        PadFrames = padFrames;
        MetadataTag = metadataTag;
    }

    /// <summary>The one-based track number, from 1 through 99.</summary>
    public uint Number { get; }
    /// <summary>The stored track data layout.</summary>
    public ChdCdTrackType Type { get; }
    /// <summary>The stored track subcode layout.</summary>
    public ChdCdSubcodeType Subtype { get; }
    /// <summary>Stored frames, including any stored pregap and excluding CHD alignment padding.</summary>
    public uint Frames { get; }
    /// <summary>The metadata pregap length, whether stored or generated by a consumer.</summary>
    public uint PregapFrames { get; }
    /// <summary>The declared layout of a stored pregap; null when the pregap is not stored, because MAME ignores
    /// PGTYPE without the V prefix, and for legacy CHTR metadata.</summary>
    public ChdCdTrackType? PregapType { get; }
    /// <summary>The declared subcode layout of a stored pregap; None when the pregap is not stored and for legacy CHTR
    /// metadata. MAME never reads it: stored pregap frames carry the track's own subcode layout, and chdman writes NONE.</summary>
    public ChdCdSubcodeType PregapSubtype { get; }
    /// <summary>Whether the pregap's frames are stored: PGTYPE has the V prefix and the pregap is not empty, as MAME reads it.</summary>
    public bool PregapStored { get; }
    /// <summary>The declared postgap length; projection does not synthesize these frames.</summary>
    public uint PostgapFrames { get; }
    /// <summary>The GD-ROM padding field; distinct from four-frame CHD alignment.</summary>
    public uint PadFrames { get; }
    /// <summary>The exact metadata tag that was parsed.</summary>
    public ChdMetadataTag MetadataTag { get; }
    /// <summary>The semantic data bytes per ordinary stored track frame.</summary>
    public int DataBytes => GetDataBytes(Type);
    /// <summary>The semantic subcode bytes per ordinary stored track frame.</summary>
    public int SubcodeBytes => Subtype == ChdCdSubcodeType.None ? 0 : 96;

    /// <summary>Parses bounded printable ASCII CHTR, CHT2, CHGD or CHGT text without allocating.</summary>
    /// <param name="tag">The exact track metadata tag.</param>
    /// <param name="metadata">At most 512 bytes, with an optional single terminating NUL.</param>
    /// <param name="track">The parsed immutable track, or default on failure.</param>
    /// <returns>False for malformed keys, unknown layouts, overflow, or invalid track bounds.</returns>
    public static bool TryParse(ChdMetadataTag tag, ReadOnlySpan<byte> metadata, out ChdCdTrack track)
    {
        track = default;
        bool legacy = tag == ChdMetadataTag.CdTrack;
        bool gd = tag == ChdMetadataTag.GdTrack || tag == ChdMetadataTag.GdTrackLegacy;
        if ((!legacy && !gd && tag != ChdMetadataTag.CdTrackV2) || metadata.IsEmpty ||
            metadata.Length > MaximumMetadataBytes) return false;
        if (metadata[^1] == 0) metadata = metadata[..^1];
        foreach (byte character in metadata)
            if (character is < 32 or > 126) return false;
        if (!Take(ref metadata, "TRACK:"u8, out ReadOnlySpan<byte> value) || !NumberValue(value, out uint number) ||
            number is 0 or > 99 || !Take(ref metadata, "TYPE:"u8, out value) || !ParseType(value, out var type) ||
            !Take(ref metadata, "SUBTYPE:"u8, out value) || !ParseSubtype(value, out var subtype) ||
            !Take(ref metadata, "FRAMES:"u8, out value) || !NumberValue(value, out uint frames) || frames == 0) return false;
        uint pad = 0, pregap = 0, postgap = 0;
        ChdCdTrackType? pregapType = null;
        ChdCdSubcodeType pregapSubtype = ChdCdSubcodeType.None;
        bool stored = false;
        if (gd && (!Take(ref metadata, "PAD:"u8, out value) || !NumberValue(value, out pad) || pad > frames)) return false;
        if (!legacy)
        {
            if (!Take(ref metadata, "PREGAP:"u8, out value) || !NumberValue(value, out pregap) ||
                !Take(ref metadata, "PGTYPE:"u8, out value)) return false;
            bool declaredStored = !value.IsEmpty && value[0] == 'V';
            if (declaredStored) value = value[1..];
            stored = declaredStored && pregap > 0;
            if (!ParseType(value, out var parsedPregap) ||
                !Take(ref metadata, "PGSUB:"u8, out value) || !ParseSubtype(value, out var parsedPregapSubtype) ||
                !Take(ref metadata, "POSTGAP:"u8, out value) || !NumberValue(value, out postgap) ||
                (stored && pregap > frames)) return false;
            if (stored) (pregapType, pregapSubtype) = (parsedPregap, parsedPregapSubtype);
        }
        if (!metadata.IsEmpty) return false;
        track = new(number, type, subtype, frames, pregap, pregapType, pregapSubtype, stored, postgap, pad, tag);
        return true;
    }

    internal static int GetDataBytes(ChdCdTrackType type) => type switch
    {
        ChdCdTrackType.Mode1 or ChdCdTrackType.Mode2Form1 => 2048,
        ChdCdTrackType.Mode2Form2 => 2324,
        ChdCdTrackType.Mode2 or ChdCdTrackType.Mode2FormMixed => 2336,
        ChdCdTrackType.Mode1Raw or ChdCdTrackType.Mode2Raw or ChdCdTrackType.Audio => 2352,
        _ => throw new ArgumentOutOfRangeException(nameof(type))
    };

    private static bool Take(ref ReadOnlySpan<byte> text, ReadOnlySpan<byte> key, out ReadOnlySpan<byte> value)
    {
        value = default;
        if (!text.StartsWith(key)) return false;
        text = text[key.Length..];
        int end = text.IndexOf((byte)' ');
        if (end < 0) { value = text; text = default; }
        else
        {
            value = text[..end];
            text = text[(end + 1)..];
            while (!text.IsEmpty && text[0] == ' ') text = text[1..];
        }
        return !value.IsEmpty;
    }

    private static bool NumberValue(ReadOnlySpan<byte> value, out uint number)
    {
        number = 0;
        if (value.IsEmpty) return false;
        foreach (byte character in value)
        {
            uint digit = (uint)(character - '0');
            if (digit > 9 || number > (uint.MaxValue - digit) / 10) return false;
            number = number * 10 + digit;
        }
        return true;
    }

    private static bool ParseType(ReadOnlySpan<byte> value, out ChdCdTrackType type)
    {
        type = default;
        if (value.SequenceEqual("MODE1"u8) || value.SequenceEqual("MODE1/2048"u8)) type = ChdCdTrackType.Mode1;
        else if (value.SequenceEqual("MODE1_RAW"u8) || value.SequenceEqual("MODE1/2352"u8)) type = ChdCdTrackType.Mode1Raw;
        else if (value.SequenceEqual("MODE2"u8) || value.SequenceEqual("MODE2/2336"u8)) type = ChdCdTrackType.Mode2;
        else if (value.SequenceEqual("MODE2_FORM1"u8) || value.SequenceEqual("MODE2/2048"u8)) type = ChdCdTrackType.Mode2Form1;
        else if (value.SequenceEqual("MODE2_FORM2"u8) || value.SequenceEqual("MODE2/2324"u8)) type = ChdCdTrackType.Mode2Form2;
        else if (value.SequenceEqual("MODE2_FORM_MIX"u8)) type = ChdCdTrackType.Mode2FormMixed;
        else if (value.SequenceEqual("MODE2_RAW"u8) || value.SequenceEqual("MODE2/2352"u8) || value.SequenceEqual("CDI/2352"u8)) type = ChdCdTrackType.Mode2Raw;
        else if (value.SequenceEqual("AUDIO"u8)) type = ChdCdTrackType.Audio;
        else return false;
        return true;
    }

    private static bool ParseSubtype(ReadOnlySpan<byte> value, out ChdCdSubcodeType subtype)
    {
        subtype = default;
        if (value.SequenceEqual("NONE"u8)) return true;
        if (value.SequenceEqual("RW"u8)) subtype = ChdCdSubcodeType.Rw;
        else if (value.SequenceEqual("RW_RAW"u8)) subtype = ChdCdSubcodeType.RwRaw;
        else return false;
        return true;
    }
}
